AWS_ACCESS_KEY_ID = 'AKIARJUDLWHEGOOX6HMN'
AWS_SECRET_ACCESS_KEY = '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'
AWS_DEFAULT_REGION = 'ap-northeast-2'
AWS_BUCKET = 'circlin-plus'
AWS_USE_PATH_STYLE_ENDPOINT = False